# Automatic management of package's version via tags using setuptools-scm

[build-system]
# Minimum versions suggested by setuptools-scm v9.2.0 docs.
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"
